CREATE DATABASE IF NOT EXISTS virtd;
CREATE USER IF NOT EXISTS 'app'@'%' IDENTIFIED BY 'QwErTy1234';
GRANT ALL PRIVILEGES ON virtd.* TO 'app'@'%';
FLUSH PRIVILEGES;

USE virtd;
CREATE TABLE IF NOT EXISTS requests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    request_date DATETIME,
    request_ip VARCHAR(255)
);
